# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/walter/Documents/code/monkeyString/ScorcsoftUI/json_format.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_json_format(object):
    def setupUi(self, json_format):
        json_format.setObjectName("json_format")
        json_format.resize(800, 600)
        json_format.setMinimumSize(QtCore.QSize(800, 600))
        json_format.setMaximumSize(QtCore.QSize(800, 16777215))
        json_format.setStyleSheet("")
        self.pushButton_start = QtWidgets.QPushButton(json_format)
        self.pushButton_start.setGeometry(QtCore.QRect(340, 550, 120, 40))
        self.pushButton_start.setObjectName("pushButton_start")
        self.plainTextEdit_source_text = QtWidgets.QPlainTextEdit(json_format)
        self.plainTextEdit_source_text.setGeometry(QtCore.QRect(10, 10, 780, 500))
        self.plainTextEdit_source_text.setObjectName("plainTextEdit_source_text")
        self.label_result = QtWidgets.QLabel(json_format)
        self.label_result.setGeometry(QtCore.QRect(10, 520, 780, 16))
        self.label_result.setObjectName("label_result")

        self.retranslateUi(json_format)
        QtCore.QMetaObject.connectSlotsByName(json_format)

    def retranslateUi(self, json_format):
        _translate = QtCore.QCoreApplication.translate
        json_format.setWindowTitle(_translate("json_format", "Form"))
        self.pushButton_start.setText(_translate("json_format", "整"))
        self.label_result.setText(_translate("json_format", "请粘贴需要格式化的JSON字符串"))
