# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/walter/Documents/code/forBy/ScorcsoftUI/page_ds_store_analyze.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_ds_store_analyze(object):
    def setupUi(self, ds_store_analyze):
        ds_store_analyze.setObjectName("ds_store_analyze")
        ds_store_analyze.resize(800, 600)
        self.label_module_name = QtWidgets.QLabel(ds_store_analyze)
        self.label_module_name.setGeometry(QtCore.QRect(10, 20, 780, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_module_name.setFont(font)
        self.label_module_name.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_module_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_module_name.setObjectName("label_module_name")
        self.lineEdit_file_path = QtWidgets.QLineEdit(ds_store_analyze)
        self.lineEdit_file_path.setGeometry(QtCore.QRect(10, 70, 686, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEdit_file_path.setFont(font)
        self.lineEdit_file_path.setWhatsThis("")
        self.lineEdit_file_path.setStyleSheet("QLineEdit { padding-left: 10px; padding-right: 10px; }")
        self.lineEdit_file_path.setCursorPosition(0)
        self.lineEdit_file_path.setObjectName("lineEdit_file_path")
        self.pushButton_start_analyze = QtWidgets.QPushButton(ds_store_analyze)
        self.pushButton_start_analyze.setGeometry(QtCore.QRect(690, 67, 100, 37))
        self.pushButton_start_analyze.setObjectName("pushButton_start_analyze")
        self.treeView_property_viewer = QtWidgets.QTreeView(ds_store_analyze)
        self.treeView_property_viewer.setGeometry(QtCore.QRect(379, 150, 411, 440))
        self.treeView_property_viewer.setObjectName("treeView_property_viewer")
        self.label_module_description = QtWidgets.QLabel(ds_store_analyze)
        self.label_module_description.setGeometry(QtCore.QRect(10, 40, 780, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_module_description.setFont(font)
        self.label_module_description.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_module_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_module_description.setObjectName("label_module_description")
        self.treeWidget_file_list = QtWidgets.QTreeWidget(ds_store_analyze)
        self.treeWidget_file_list.setGeometry(QtCore.QRect(10, 150, 368, 440))
        self.treeWidget_file_list.setObjectName("treeWidget_file_list")
        self.treeWidget_file_list.headerItem().setText(0, "1")
        self.label_file_list = QtWidgets.QLabel(ds_store_analyze)
        self.label_file_list.setGeometry(QtCore.QRect(10, 125, 468, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_file_list.setFont(font)
        self.label_file_list.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_file_list.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_file_list.setObjectName("label_file_list")
        self.label_property = QtWidgets.QLabel(ds_store_analyze)
        self.label_property.setGeometry(QtCore.QRect(379, 125, 312, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.label_property.setFont(font)
        self.label_property.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_property.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_property.setObjectName("label_property")

        self.retranslateUi(ds_store_analyze)
        QtCore.QMetaObject.connectSlotsByName(ds_store_analyze)

    def retranslateUi(self, ds_store_analyze):
        _translate = QtCore.QCoreApplication.translate
        ds_store_analyze.setWindowTitle(_translate("ds_store_analyze", "Form"))
        self.label_module_name.setText(_translate("ds_store_analyze", "DS_Store 解析"))
        self.lineEdit_file_path.setPlaceholderText(_translate("ds_store_analyze", "输入本地 .DS_Store 文件路径 Or .DS_Store 文件的 URL (例如：https://scorcsoft.com/.DS_Store)"))
        self.pushButton_start_analyze.setText(_translate("ds_store_analyze", "开始"))
        self.label_module_description.setText(_translate("ds_store_analyze", ".DS_Store文件泄露漏洞利用工具，解析.DS_Store内容全自动递归还原网站目录结构。"))
        self.label_file_list.setText(_translate("ds_store_analyze", "解析出的文件或目录清单："))
        self.label_property.setText(_translate("ds_store_analyze", "在文件或目录上右键菜单可以查看它的具体属性："))
