# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/Users/walter/Documents/code/forBy/ScorcsoftUI/page_svn_directory_analyze.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_svn_directory_analyze(object):
    def setupUi(self, svn_directory_analyze):
        svn_directory_analyze.setObjectName("svn_directory_analyze")
        svn_directory_analyze.resize(800, 600)
        self.label_module_name = QtWidgets.QLabel(svn_directory_analyze)
        self.label_module_name.setGeometry(QtCore.QRect(10, 20, 780, 20))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.label_module_name.setFont(font)
        self.label_module_name.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_module_name.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_module_name.setObjectName("label_module_name")
        self.label_module_description = QtWidgets.QLabel(svn_directory_analyze)
        self.label_module_description.setGeometry(QtCore.QRect(10, 40, 780, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_module_description.setFont(font)
        self.label_module_description.setLocale(QtCore.QLocale(QtCore.QLocale.Chinese, QtCore.QLocale.China))
        self.label_module_description.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_module_description.setObjectName("label_module_description")
        self.label = QtWidgets.QLabel(svn_directory_analyze)
        self.label.setGeometry(QtCore.QRect(0, 140, 800, 91))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(svn_directory_analyze)
        self.label_2.setGeometry(QtCore.QRect(0, 290, 800, 91))
        font = QtGui.QFont()
        font.setPointSize(64)
        self.label_2.setFont(font)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")

        self.retranslateUi(svn_directory_analyze)
        QtCore.QMetaObject.connectSlotsByName(svn_directory_analyze)

    def retranslateUi(self, svn_directory_analyze):
        _translate = QtCore.QCoreApplication.translate
        svn_directory_analyze.setWindowTitle(_translate("svn_directory_analyze", "Form"))
        self.label_module_name.setText(_translate("svn_directory_analyze", ".svn 解析"))
        self.label_module_description.setText(_translate("svn_directory_analyze", ".svn目录泄露漏洞利用工具，解析.git目录内容查看敏感信息。"))
        self.label.setText(_translate("svn_directory_analyze", "还没做！！！"))
        self.label_2.setText(_translate("svn_directory_analyze", "太忙了最近。"))
